# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f3c1562fe21c816e2db8aa49558f9b58"
application_url = "https://70a4-121-67-5-167.ngrok-free.app/"
embedded = true
name = "고로켓 개발 앱"
handle = "gorocket-dev"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/shop-redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://70a4-121-67-5-167.ngrok-free.app/authenticate" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
